"""Add sets and reps to WorkoutPlan

Revision ID: 297a3326b08e
Revises: 6151020f7beb
Create Date: 2025-05-03 02:56:53.513684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297a3326b08e'
down_revision = '6151020f7beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')

    # ### end Alembic commands ###
