"""Create WorkoutPlan table

Revision ID: 6151020f7beb
Revises: 
Create Date: 2025-05-03 02:09:26.604529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6151020f7beb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_plan_day_of_week'), ['day_of_week'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_plan_day_of_week'))

    op.drop_table('workout_plan')
    # ### end Alembic commands ###
