"""Add SharedPlan table and temporarily adjust WorkoutPlan user_id

Revision ID: 6a71202cf7d9
Revises: 833c49655118
Create Date: 2025-05-11 18:46:16.820889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a71202cf7d9'
down_revision = '833c49655118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sharer_id', sa.Integer(), nullable=False),
    sa.Column('recipient_identifier', sa.String(length=120), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_plan_recipient_identifier'), ['recipient_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_plan_sharer_id'), ['sharer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_plan_sharer_id'))
        batch_op.drop_index(batch_op.f('ix_shared_plan_recipient_identifier'))

    op.drop_table('shared_plan')
    # ### end Alembic commands ###
