"""Add user_id to WorkoutPlan (without FK for now)

Revision ID: 833c49655118
Revises: 3bc64480fe9b
Create Date: 2025-05-11 17:58:25.442012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833c49655118'
down_revision = '3bc64480fe9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_workout_plan_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_plan_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
