"""add weight to workout_plan

Revision ID: e80847f4fa3a
Revises: ef640b585759
Create Date: 2025-05-14 19:41:35.738219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80847f4fa3a'
down_revision = 'ef640b585759'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_column('weight')
