"""Add relationships and foreign keys for User, WorkoutPlan, SharedPlan

Revision ID: ef640b585759
Revises: 6a71202cf7d9
Create Date: 2025-05-12 21:54:53.896317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef640b585759'
down_revision = '6a71202cf7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_shared_plan_recipient_identifier')
        batch_op.create_index(batch_op.f('ix_shared_plan_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_foreign_key('fk_shared_plan_sharer_id_users', 'users', ['sharer_id'], ['id'])
        batch_op.create_foreign_key('fk_shared_plan_recipient_id_users', 'users', ['recipient_id'], ['id'])
        batch_op.drop_column('recipient_identifier')

    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_set', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_workout_plan_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('calories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_workout_plan_user_id_users', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('calories_per_set')

    with op.batch_alter_table('shared_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_identifier', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint('fk_shared_plan_recipient_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_shared_plan_sharer_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shared_plan_recipient_id'))
        batch_op.create_index('ix_shared_plan_recipient_identifier', ['recipient_identifier'], unique=False)
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
